import Head from "next/head";
import { useSession, signOut } from "next-auth/react";
import Link from "next/link";
import { CustomNextPage } from "../types/CustomNextPage";

const Home: CustomNextPage = () => {
  const { data, status } = useSession();

  return (
    <>
      <Head>
        <title>Magnus Centar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        {data?.user?.name || <Link href="/auth/signin">SIGN IN</Link>}{" "}
        {status === "authenticated" && (
          <button onClick={() => signOut()}>SIGN OUT</button>
        )}
        <Link legacyBehavior href="/categories">
          <a style={{ marginLeft: "1rem" }}>PROTECTED PAGE</a>
        </Link>
      </main>
    </>
  );
};

Home.requireAuth = true;
export default Home;
