import Head from "next/head";
import { useSession, signOut } from "next-auth/react";
import Link from "next/link";

export default function Home() {
  const { data, status } = useSession();

  return (
    <>
      <Head>
        <title>Magnus Centar</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        {data?.user?.name || <Link href="/auth/signin">SIGN IN</Link>}{" "}
        {status === "authenticated" && (
          <button onClick={() => signOut()}>SIGN OUT</button>
        )}
      </main>
    </>
  );
}
